export const customer_info_person_form_data = {
  mobile: "",
  nationality: "",
  nation: "",
  // remark2: "",
  // ccy: "",
  vocation: "",
  // post: "",
  entId: "",
  industry: "",
  // dept: "",
  front: "",
  back: "",
  dom: "",
  age: "",
  esdate: "",
  remark: "",
  // postAddr: "",
  custName: "",
  pastName: "",
  certType: "0",
  certNo: "",
  signOffice: "",
  certDate: [],
  certBeginDate: "",
  certEndDate: "",
  businessTerm: "",
  // pmtAddrProvinceCode: "",
  // pmtAddrCityCode: "",
  // pmtAddrAreaCode: "",
  certAddress: "",
  eduLevel: "",
  highestDegree: "",
  gradSchool: "",
  gradYear: "",
  marryStatus: "",
  hasChildren: "",
  // urgentLinkMan: "",
  // urgentLinkRelation: "",
  // urgentLinkMobile: "",
  birthday: "",
  sex: "",
  liveTime: "",
  liveHouseCondition: "",
  liveCarCondition: 1,
  liveAddressDetail: "",
  localHouse: "",
  homePhone: "",
  liveStatus: "",
  liveProvinceCode: "",
  liveCityCode: "",
  liveAreaCode: "",
  isPaySecurity: "",
  residZipCode: "",
  monthIncome: "",
  annualIncome: "",
  otherIncome: "",
  familyAnnualIncome: "",
  positionalTitles: "",
  unitProperty: "",
  customerInfoContacts:[
    {relation:"",name:"",mobile:""},
    {relation:"",name:"",mobile:""},
  ],
  oftenEmail:"",
  familyAddressDetail:"",
  workYears:1,
  workUnitName: "",
  workUnitTelphone: "",
  workAddressDetail: "",  
  workAddrProvinceCode: "",
  workAddrCityCode: "",
  workAddrAreaCode: "",
  workAddrAddress: "",
  workDist: "",
  workZip: "",
  workBeginDate: "",
  workYear: "",
  frontKey: "",
  reverseKey: "",
  authCode: "",
  industryDetailCode: "",
  entLicenseNo: "",
  entCertificateNo: "",
  taxPayerId: "",
  companyMonthlyTax: "",
  orgBranchCode: "",
  busiRegisterNo: "",
  businessCode: "",
  openLicenceNo: "",
  businRegiDate: "",
  fundingCurrency: "",
  fundingAmt: "",
  enterpriseScale: "",
  entType: "",
  businessPlace: "",
  businessManager: "",
  businessScope: "",
  industryCode: "",
  industryCode1: "",
  industryCode2: "",
  industryCode3: "",
  industryCode4: "",
  paidupCapital: "",
  licenseNo: "",
  dobusinessIdentity: "",
  dobusinessCity: "",
  dobusinessStatus: "",
  regProvinceCode: "",
  regCityCode: "",
  regAreaCode: "",
  officeProvinceCode: "",
  officeCityCode: "",
  officeAreaCode: "",
  regAddress: "",
  officeAddress: "",
  legalName: "",
  legalCertificateKind: "",
  legalCertificateNo: "",
  legalMobileNo: "",
  legalPersonAddress: "",
  legalPersonProvince: "",
  legalPersonCity: "",
  legalPersonOffice: "",
  legalPersonFit: "",
  publishDate: "",
  invalidDate: "",
  companyTaxpayerNo: "",
  localTaxpayerNo: "",
  taxPayProvinceCode: "",
  taxPayCityCode: "",
  taxPayAreaCode: "",
  taxLoginName: "",
  taxLoginPassword: "",
  authenticationType: "",
  authenticationStatus: "",
  empowerStatus: "",
  regorgCn: "",
  taxArea: "",
  apprDate: "",
  loanUse: "",
  loanAmt: "",
  loanPeriod: "",
  rowVersion: "1",
  entName:"",
  entCreateDate:"",
  applyRef:"",
}

// export interface personRuleForm {
//   mobile: string,
//   nationality: string
//   nation: string,
//   remark2: string,
//   ccy: string,
//   vocation: string,
//   post: string,
//   entId: string,
//   industry: string,
//   dept: string,
//   front: string,
//   back: string,
//   dom: string,
//   age: string,
//   esdate: string,
//   remark: string,
//   postAddr: string,
//   custName: string,
//   pastName: string,
//   certType: string,
//   signOffice: string,
//   certBeginDate: string,
//   certEndDate: string,
//   businessTerm: string,
//   pmtAddrProvinceCode: string,
//   pmtAddrCityCode: string,
//   pmtAddrAreaCode: string,
//   certAddress: string,
//   eduLevel: string,
//   highestDegree: string,
//   gradSchool: string,
//   gradYear: string,
//   marryStatus: string,
//   hasChildren: string,
//   // urgentLinkMan: string,
//   // urgentLinkRelation: string,
//   // urgentLinkMobile: string,
//   birthday: string,
//   liveTime: string,
//   liveHouseCondition: string,
//   liveCarCondition: string,
//   liveAddressDetail: string,
//   localHouse: string,
//   homePhone: string,
//   liveStatus: string,
//   liveProvinceCode: string,
//   liveCityCode: string,
//   liveAreaCode: string,
//   isPaySecurity: string,
//   residZipCode: string,
//   monthIncome: string,
//   annualIncome: string,
//   otherIncome: string,
//   familyAnnualIncome: string,
//   positionalTitles: string,
//   unitProperty: string,
//   customerInfoContacts:Array<Object>,
//   oftenEmail:string,
//   familyAddressDetail:string,
//   workYears:number,
// }